services:
  auth-server:
    build: ./server
    container_name: barbershop-auth
    ports:
      - "9000:9000"
    env_file:
      - ./server/.env
    environment:
      BUSINESS_API_URL: http://business-api:8080
      APP_BASE_URL: http://127.0.0.1:9000
      APP_REDIRECT_URI: http://127.0.0.1:8090/login/oauth2/code/barberia-client
      APP_FRONTEND_URL: ${FRONTEND_URL}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s

  business-api:
    build: ./project
    container_name: barbershop-business
    ports:
      - "8080:8080"
    env_file:
      - ./project/.env
    environment:
      AUTH_SERVER_URL: http://auth-server:9000
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-server:9000/oauth2/jwks
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      auth-server:
        condition: service_healthy

  bff:
    build: ./bff
    container_name: barbershop-bff
    ports:
      - "8090:8090"
    env_file:
      - ./bff/.env
    environment:
      AUTH_SERVER_URL: http://auth-server:9000
      AUTH_SERVER_PUBLIC_URL: http://127.0.0.1:9000
      BARBERIA_API_URL: http://business-api:8080
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_URL_ALT: ${FRONTEND_URL}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      auth-server:
        condition: service_healthy
      business-api:
        condition: service_started

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      config:
        - subnet: 172.20.0.0/16
