server:
  port: ${BFF_PORT:8090}

app:
  frontend-url: ${FRONTEND_URL:http://127.0.0.1:5173}

spring:
  config:
    import: optional:file:.env[.properties]
  session:
    store-type: redis
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      ssl:
        enabled: true
  main:
    web-application-type: reactive
  application:
    name: barberia-bff

  security:
    oauth2:
      client:
        registration:
          barberia-client:
            provider: barberia-auth-server
            client-id: ${OAUTH2_CLIENT_ID:barberia-client}
            client-secret: ${OAUTH2_CLIENT_SECRET:123456}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
            client-authentication-method: client_secret_basic
        provider:
          barberia-auth-server:
            issuer-uri: ${AUTH_SERVER_PUBLIC_URL:http://127.0.0.1:9000}
            user-name-attribute: sub

  cloud:
    gateway:
      routes:
        - id: auth-server-users
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/users/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

        - id: auth-server-public
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/register, /api/auth/verify-email, /api/auth/forgot-password, /api/auth/verify-otp, /api/auth/reset-password
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
            - RemoveRequestHeader=Cookie

        - id: auth-server-auth
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

        - id: api-barberia
          uri: ${BARBERIA_API_URL:http://localhost:8080}
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL:http://localhost:5173}
              - ${FRONTEND_URL_ALT:http://127.0.0.1:5173}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true


logging:
  level:
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.security.web: TRACE